-- Drop Tables
Drop Table Cliente Cascade Constraints ;Drop Table Filme Cascade Constraints ;Drop Table Locacao Cascade Constraints ;Drop Table Papel Cascade Constraints ;Drop Table Participacao Cascade Constraints ;Drop Table Profissional_Cinema Cascade Constraints ;Purge Recyclebin ;

-- TABLE: CLIENTE
Create Table Cliente
(
    Cod_Cliente     Number Generated By Default As Identity,
    Cliente_Titular Number(10, 0),
    Nome            Varchar2(60) Not Null,
    Telefone        Varchar2(20),
    Endereco        Varchar2(60),
    Cidade          Varchar2(20) Default 'Bicas',
    Uf              Char(2) Default 'MG' Constraint Ck_Cliente_01 Check (Uf In ('SP',
                                                                          'MG',
                                                                          'RJ',
                                                                          'ES')),
    Email Varchar2(100),
    Constraint Pk_Cliente Primary Key (Cod_Cliente)
) ;

-- TABLE: FILME
Create Table Filme
(
    Cod_Filme              Number Generated By Default As Identity,
    Nome                   Varchar2(100) Not Null,
    Nome_Original          Varchar2(100),
    Ano                    Number(4, 0) Constraint Ck_Filme_01 Check (Ano > 1900),
    Duracao_Minutos        Number(3, 0) Constraint Ck_Filme_02 Check (Duracao_Minutos Between 10 And          300),
    Preco_Sugerido_Locacao Number(7, 2),
    Censura                Number(2, 0) Default 18 Constraint Ck_Filme_03 Check (Censura Between 0 And          18),
    Constraint Pk_Filme Primary Key (Cod_Filme)
) ;
             
-- TABLE: LOCACAO
Create Table Locacao
(
    Cod_Filme      Number(10, 0) Not Null,
    Cod_Cliente    Number(10, 0) Not Null,
    Dt_Locacao     Date Not Null,
    Preco_Aplicado Number(9, 2)
) ;

--
-- TABLE: PAPEL
Create Table Papel
(
    Cod_Papel Number Generated By Default As Identity,
    Descricao Varchar2(60) Not Null,
    Constraint Pk_Papel Primary Key (Cod_Papel),
    Constraint U_Papel_01 Unique (Descricao)
) ;

--
-- TABLE: PARTICIPACAO
Create Table Participacao
(
    Cod_Papel               Number(10, 0) Not Null,
    Cod_Profissional_Cinema Number(10, 0) Not Null,
    Cod_Filme               Number(10, 0) Not Null,
    Constraint Pk_Participacao Primary Key (Cod_Papel, Cod_Profissional_Cinema, Cod_Filme)
) ;

--
-- TABLE: PROFISSIONAL_CINEMA
Create Table Profissional_Cinema
(
    Cod_Profissional_Cinema Number Generated By Default As Identity,
    Nome                    Varchar2(30) Not Null,
    Dt_Nascimento           Date,
    Pais_Origem             Varchar2(20),
    Constraint Pk_Profissional_Cinema Primary Key (Cod_Profissional_Cinema)
) ;

--
-- TABLE: CLIENTE
Alter Table Cliente Add Constraint Fk_Cliente_01 Foreign Key (Cliente_Titular) References Cliente(Cod_Cliente) ;

--
-- TABLE: LOCACAO
Alter Table Locacao Add Constraint Fk_Locacao_01 Foreign Key (Cod_Cliente) References Cliente(Cod_Cliente) ;Alter Table Locacao Add Constraint Fk_Locacao_02 Foreign Key (Cod_Filme) References Filme(Cod_Filme) ;

--
-- TABLE: PARTICIPACAO
Alter Table Participacao Add Constraint Fk_Participacao_01 Foreign Key (Cod_Filme) References Filme(Cod_Filme) ;Alter Table Participacao Add Constraint Fk_Participacao_02 Foreign Key (Cod_Papel) References Papel(Cod_Papel) ;Alter Table Participacao Add Constraint Fk_Participacao_03 Foreign Key (Cod_Profissional_Cinema) References Profissional_Cinema(Cod_Profissional_Cinema) ;